setup_anspass: check the credentials in anspass database
Issue: LINUXEXEC-10887

Previously, the anspass database always exists in an project
which has run setup program before. It's annoying when user has
changed the credentials and has no chance to reinput the new one
though the old one in anspass database is already incorrect.

Check the credentials first and let user choose to remove the
anspass database to reinput the new one if the old credentials
in anspass database not correct.

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>

diff --git a/data/environment.d/setup_anspass b/data/environment.d/setup_anspass
--- a/data/environment.d/setup_anspass
+++ b/data/environment.d/setup_anspass
@@ -61,6 +61,33 @@ anspass_transfer_dump() {
 	eval echo \${password_${murl}}
 }
 
+anspass_check_credential() {
+	err=$(LANG=C git ls-remote $REMOTEURL 2>&1 >/dev/null)
+	ret=$?
+	if [ $ret -ne 0 ] && [ "${err}" != "${err/Authentication/}" ]; then
+		echo
+		echo "${err}"
+		while true ; do
+			echo
+			echo "The saved user or password seems invalid, remove it and try again?"
+			read -p "Remove the anspass db bin/.anspass? [Yes/No]" accept
+			case ${accept} in
+				[yY][eE][sS])
+					anspass_stop
+					rm -rf ${PWD}/bin/.anspass
+					break
+					;;
+				[nN][oO])
+					break
+					;;
+				*)
+					echo "Only yes and no are accepted." >&2
+					;;
+			esac
+		done
+	fi
+}
+
 anspass_start() {
 	# Do we have anspassd available yet?
 	if ! which anspassd >/dev/null 2>&1 ; then
@@ -133,6 +160,9 @@ EOF
 	fi
 	export GIT_ASKPASS=$(which anspass)
 	export SSH_ASKPASS=$(which anspass)
+
+	# check the old credentials works or not
+	anspass_check_credential
 }
 
 anspass_stop() {
