setup_anspass: If anspassd failed to start, detect it
If anspassd can't start for some reason, detect the condition and alert the
user.

Note: there was a bug in anspass.  This patch will deadlock on older
versions, prior to commit 2060077626efafeda41b2f1c678dd5bb89708d0c.

buildtools-standalone-20161203 or newer is required.

Signed-off-by: Mark Hatle <mark.hatle@windriver.com>

diff --git a/data/environment.d/setup_anspass b/data/environment.d/setup_anspass
--- a/data/environment.d/setup_anspass
+++ b/data/environment.d/setup_anspass
@@ -75,7 +75,13 @@ anspass_setup() {
 	echo "Enabling anspass..."
 
 	export ANSPASS_PATH=${PWD}/bin/.anspass
-	export ANSPASS_TOKEN=$(anspassd < /dev/null | head -n 1 | sed 's,Token: ,,')
+	result=$(anspassd < /dev/null 2>&1)
+	if [ $? -ne 0 ]; then
+		echo "anspassd failed to start:"
+		echo "${result}"
+		return 1
+	fi
+	export ANSPASS_TOKEN=$(echo "$result" | grep "Token:" | head -n 1 | sed 's,Token: ,,')
 	echo "Token: ${ANSPASS_TOKEN}"
 	wrl_anspass_started=1
 
